### ISSUE TITLE
Strange Instruments

### ISSUE THREAD

**Issue by TorutheRedFox** [ValleyBell/SMPSPlay#6] opened 2018-12-08 17:46 UTC
I've noticed that Ice Cap Zone (both acts) have an instrument that only plays once, and is way too loud, and another time with songs that I converted to Michael Jackson's Moonwalker usually play random notes at the start and end (and not when played in the actual game)

**Comment by ValleyBell** [comment] 2018-12-18 09:37
About the Ice Cap Zone bug: Are you sure this still happens in v2.20? I didn't notice anything unusual.  
Can you give me a timestamp of where it happens in the song?

About the MJMM bug: I'll need your converted songs to recreate and investigate the bug.

**Comment by TorutheRedFox** [comment] 2018-12-18 17:24
I don't have v2.20 because idk how to build it and can't find a build, and about the MJMW bug, here's one of the files that trigger the bug 
[Title.zip](https://github.com/ValleyBell/SMPSPlay/files/2691566/Title.zip)
(btw, it's not actually a zip file, I just renamed the extension to zip to satisfy GitHub)

**Comment by ValleyBell** [comment] 2018-12-18 22:24
The MJMW is fixed with cf7b11fe91006e0a6d4b2e88f7b649841c940ad3. It was a small oversight that caused the Track End command (F2) to write invalid FM note commands when executed on a PSG channel - sorry.  
The bug only affects the "silence + track end" command. (byte F2 in SMPS 68k/Type 1a, byte E3 in all other SMPS versions)

> I don't have v2.20 because idk how to build it and can't find a build

Searching for "smpsplay 2.20" should lead you to a topic on the Sonic Retro forums where I post all builds.  
As for the new bugfix - I'm afraid you'll have to build SMPSPlay by yourself in order to get that one.

I'll close the issue for now, because I'm unable to reproduce bug 1 in the current version (I think bb4f2300cf07b880ada7b6957fd3ddd6e3150316 should've fixed it) and bug 2 I just fixed.

**Closed as completed by ValleyBell** 2018-12-18 22:24 UTC
